In [1]:
import numpy as np

contexts = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [10, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 10, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 0, 10]
])
items_ids = np.array([
    'abacate',
    'abacate',
    'abacate',
    'abacate',
    'banana',
    'banana',
    'banana',
    'banana',
    'laranja',
    'laranja',
    'laranja',
    'laranja'
])
rewards = np.array([
    1,
    0,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1
])

In [2]:
import gobrec

In [3]:
lin_gobrec = gobrec.mabs.lin_mabs.Lin(seed=1, items_per_batch=1)

In [4]:
lin_gobrec.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [5]:
lin_gobrec.predict(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

tensor([[0.1078, 0.0000, 0.0000],
        [0.0000, 0.1078, 0.0000],
        [0.0000, 0.0000, 0.1078],
        [1.0784, 0.0000, 0.0000],
        [0.0000, 1.0784, 0.0000],
        [0.0000, 0.0000, 1.0784]], dtype=torch.float64)

In [6]:
gobrec_recommender = gobrec.Recommender(
    mab_algo=gobrec.mabs.lin_mabs.Lin(seed=1, items_per_batch=1),
    top_k=3
)

In [7]:
gobrec_recommender.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [8]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

(array([['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana']], dtype='<U7'),
 array([[0.10784314, 0.        , 0.        ],
        [0.10784314, 0.        , 0.        ],
        [0.10784314, 0.        , 0.        ],
        [1.07843137, 0.        , 0.        ],
        [1.07843137, 0.        , 0.        ],
        [1.07843137, 0.        , 0.        ]]))

In [9]:
import mab2rec

In [10]:
mab2rec_recommender = mab2rec.BanditRecommender(learning_policy=mab2rec.LearningPolicy.LinGreedy(epsilon=0), top_k=3)
mab2rec_recommender.fit(
    contexts=contexts,
    decisions=items_ids,
    rewards=rewards
)

In [11]:
mab2rec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    return_scores=True,
    apply_sigmoid=False
)

([['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate'],
  ['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate']],
 [[0.10784313725490197, 0.0, 0.0],
  [0.10784313725490197, 0.0, 0.0],
  [0.10784313725490197, 0.0, 0.0],
  [1.0784313725490198, 0.0, 0.0],
  [1.0784313725490198, 0.0, 0.0],
  [1.0784313725490198, 0.0, 0.0]])

In [12]:
gobrec_recommender = gobrec.Recommender(
    mab_algo=gobrec.mabs.lin_mabs.LinUCB(alpha=0.1, seed=1, items_per_batch=1),
    top_k=3
)

In [13]:
gobrec_recommender.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [14]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

(array([['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana']], dtype='<U7'),
 array([[0.11774461, 0.07071068, 0.07071068],
        [0.11774461, 0.07071068, 0.07071068],
        [0.11774461, 0.07071068, 0.07071068],
        [1.17744613, 0.70710678, 0.70710678],
        [1.17744613, 0.70710678, 0.70710678],
        [1.17744613, 0.70710678, 0.70710678]]))

In [15]:
mab2rec_recommender = mab2rec.BanditRecommender(learning_policy=mab2rec.LearningPolicy.LinUCB(alpha=0.1), top_k=3)
mab2rec_recommender.fit(
    contexts=contexts,
    decisions=items_ids,
    rewards=rewards
)

In [16]:
mab2rec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    return_scores=True,
    apply_sigmoid=False
)

([['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate'],
  ['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate']],
 [[0.11774461268466871, 0.07071067811865477, 0.07071067811865477],
  [0.11774461268466871, 0.07071067811865477, 0.07071067811865477],
  [0.11774461268466871, 0.07071067811865477, 0.07071067811865477],
  [1.1774461268466871, 0.7071067811865476, 0.7071067811865476],
  [1.1774461268466871, 0.7071067811865476, 0.7071067811865476],
  [1.1774461268466871, 0.7071067811865476, 0.7071067811865476]])

In [17]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    items_ids_filter=[
        np.array([0, 1, 2]),
        np.array(['abacate', 'banana', 'laranja'])
    ]
)

(array([['banana', 'laranja', 'abacate'],
        ['abacate', 'laranja', 'banana'],
        ['abacate', 'banana', 'laranja'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana']], dtype='<U7'),
 array([[ 7.07106781e-02,  7.07106781e-02, -1.00000000e+02],
        [ 7.07106781e-02,  7.07106781e-02, -1.00000000e+02],
        [ 7.07106781e-02,  7.07106781e-02, -1.00000000e+02],
        [ 1.17744613e+00,  7.07106781e-01,  7.07106781e-01],
        [ 1.17744613e+00,  7.07106781e-01,  7.07106781e-01],
        [ 1.17744613e+00,  7.07106781e-01,  7.07106781e-01]]))

In [18]:
gobrec_recommender = gobrec.Recommender(
    mab_algo=gobrec.mabs.lin_mabs.LinGreedy(seed=1, items_per_batch=1, epsilon=0.6),
    top_k=3
)

In [19]:
gobrec_recommender.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [20]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

(array([['abacate', 'laranja', 'banana'],
        ['banana', 'abacate', 'laranja'],
        ['banana', 'laranja', 'abacate'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['abacate', 'laranja', 'banana']], dtype='<U7'),
 array([[0.82770259, 0.54959369, 0.40919914],
        [0.10784314, 0.        , 0.        ],
        [0.75351311, 0.53814331, 0.02755911],
        [1.07843137, 0.        , 0.        ],
        [0.7884287 , 0.32973172, 0.30319483],
        [0.45349789, 0.40311299, 0.1340417 ]]))

In [21]:
mab2rec_recommender = mab2rec.BanditRecommender(learning_policy=mab2rec.LearningPolicy.LinGreedy(epsilon=0.6), top_k=3, seed=1)
mab2rec_recommender.fit(
    contexts=contexts,
    decisions=items_ids,
    rewards=rewards
)

In [22]:
mab2rec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    return_scores=True,
    apply_sigmoid=False
)

([['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['banana', 'laranja', 'abacate'],
  ['abacate', 'laranja', 'banana'],
  ['banana', 'abacate', 'laranja'],
  ['abacate', 'laranja', 'banana']],
 [[0.8277025938204418, 0.5495936876730595, 0.4091991363691613],
  [0.10784313725490197, 0.0, 0.0],
  [0.7535131086748066, 0.5381433132192782, 0.027559113243068367],
  [1.0784313725490198, 0.0, 0.0],
  [0.7884287034284043, 0.32973171649909216, 0.303194829291645],
  [0.4534978894806515, 0.40311298644712923, 0.13404169724716475]])

In [23]:
gobrec_recommender = gobrec.Recommender(
    mab_algo=gobrec.mabs.lin_mabs.LinTS(seed=1, items_per_batch=1, alpha=0.1),
    top_k=3
)

In [24]:
gobrec_recommender.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [25]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

(array([['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana']], dtype='<U7'),
 array([[ 0.11126493,  0.02443649,  0.02443649],
        [ 0.1168075 ,  0.06401833,  0.06401833],
        [ 0.11145294,  0.02577916,  0.02577916],
        [ 1.10755483,  0.20798308,  0.20798308],
        [ 1.06230088, -0.11519473, -0.11519473],
        [ 1.04947384, -0.20679815, -0.20679815]]))

In [26]:
mab2rec_recommender = mab2rec.BanditRecommender(learning_policy=mab2rec.LearningPolicy.LinTS(alpha=0.1), top_k=3, seed=1)
mab2rec_recommender.fit(
    contexts=contexts,
    decisions=items_ids,
    rewards=rewards
)

In [27]:
mab2rec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    return_scores=True,
    apply_sigmoid=False
)

([['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate'],
  ['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate']],
 [[0.11126493064154723, 0.024436492567988452, 0.024436492567988452],
  [0.11680749612396102, 0.06401832727115855, 0.06401832727115855],
  [0.11145294187810958, 0.02577916135766028, 0.02577916135766028],
  [1.107554829436326, 0.207983082952452, 0.207983082952452],
  [1.0623008840758417, -0.11519472894863544, -0.11519472894863544],
  [1.0494738392095173, -0.20679815181119957, -0.20679815181119957]])