In [1]:
import numpy as np

contexts = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [10, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 10, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
    [0, 0, 10]
])
items_ids = np.array([
    'abacate',
    'abacate',
    'abacate',
    'abacate',
    'banana',
    'banana',
    'banana',
    'banana',
    'laranja',
    'laranja',
    'laranja',
    'laranja'
])
rewards = np.array([
    1,
    0,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1
])

In [2]:
import gobrec

In [3]:
lin_gobrec = gobrec.mabs.lin_mabs.Lin(seed=1)

In [4]:
lin_gobrec.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [5]:
lin_gobrec.predict(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

tensor([[0.1078, 0.0000, 0.0000],
        [0.0000, 0.1078, 0.0000],
        [0.0000, 0.0000, 0.1078],
        [1.0784, 0.0000, 0.0000],
        [0.0000, 1.0784, 0.0000],
        [0.0000, 0.0000, 1.0784]], dtype=torch.float64)

In [6]:
gobrec_recommender = gobrec.Recommender(
    mab_algo=gobrec.mabs.lin_mabs.Lin(seed=1),
    top_k=3
)

In [7]:
gobrec_recommender.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [8]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

(array([['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana']], dtype='<U7'),
 array([[0.10784314, 0.        , 0.        ],
        [0.10784314, 0.        , 0.        ],
        [0.10784314, 0.        , 0.        ],
        [1.07843137, 0.        , 0.        ],
        [1.07843137, 0.        , 0.        ],
        [1.07843137, 0.        , 0.        ]]))

In [9]:
import mab2rec

In [10]:
mab2rec_recommender = mab2rec.BanditRecommender(learning_policy=mab2rec.LearningPolicy.LinGreedy(epsilon=0), top_k=3)
mab2rec_recommender.fit(
    contexts=contexts,
    decisions=items_ids,
    rewards=rewards
)

In [11]:
mab2rec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    return_scores=True,
    apply_sigmoid=False
)

([['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate'],
  ['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate']],
 [[0.10784313725490197, 0.0, 0.0],
  [0.10784313725490197, 0.0, 0.0],
  [0.10784313725490197, 0.0, 0.0],
  [1.0784313725490198, 0.0, 0.0],
  [1.0784313725490198, 0.0, 0.0],
  [1.0784313725490198, 0.0, 0.0]])

In [15]:
gobrec_recommender = gobrec.Recommender(
    mab_algo=gobrec.mabs.lin_mabs.LinUCB(alpha=0.1, seed=1),
    top_k=3
)

In [16]:
gobrec_recommender.fit(
    contexts=contexts,
    items_ids=items_ids,
    rewards=rewards
)

In [17]:
gobrec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ])
)

(array([['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana'],
        ['abacate', 'banana', 'laranja'],
        ['banana', 'abacate', 'laranja'],
        ['laranja', 'abacate', 'banana']], dtype='<U7'),
 array([[0.11774461, 0.07071068, 0.07071068],
        [0.11774461, 0.07071068, 0.07071068],
        [0.11774461, 0.07071068, 0.07071068],
        [1.17744613, 0.70710678, 0.70710678],
        [1.17744613, 0.70710678, 0.70710678],
        [1.17744613, 0.70710678, 0.70710678]]))

In [18]:
mab2rec_recommender = mab2rec.BanditRecommender(learning_policy=mab2rec.LearningPolicy.LinUCB(alpha=0.1), top_k=3)
mab2rec_recommender.fit(
    contexts=contexts,
    decisions=items_ids,
    rewards=rewards
)

In [19]:
mab2rec_recommender.recommend(
    contexts=np.array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [10, 0, 0],
        [0, 10, 0],
        [0, 0, 10]
    ]),
    return_scores=True,
    apply_sigmoid=False
)

([['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate'],
  ['abacate', 'laranja', 'banana'],
  ['banana', 'laranja', 'abacate'],
  ['laranja', 'banana', 'abacate']],
 [[0.11774461268466871, 0.07071067811865477, 0.07071067811865477],
  [0.11774461268466871, 0.07071067811865477, 0.07071067811865477],
  [0.11774461268466871, 0.07071067811865477, 0.07071067811865477],
  [1.1774461268466871, 0.7071067811865476, 0.7071067811865476],
  [1.1774461268466871, 0.7071067811865476, 0.7071067811865476],
  [1.1774461268466871, 0.7071067811865476, 0.7071067811865476]])